"""
Cleanup script for demo/sample trading partner rows.

Targets only the known fake vendor set created by seed_demo_data() and
app/db/seed.py.  Rows with real DSCSA identifiers (GLN, DEA number, or
state license number) are ALWAYS skipped regardless of name or email.

Usage:
    # Dry-run (default) — prints what would be removed, deletes nothing:
    python scripts/cleanup_sample_partners.py

    # Actually delete:
    python scripts/cleanup_sample_partners.py --apply
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db.session import SessionLocal
from app.db.models import Vendor

# Exact names from seed_demo_data() in session.py and seed.py
SAMPLE_NAMES = {
    "teva pharmaceuticals",
    "sandoz inc",
    "dr. reddy's laboratories",
    "capsugel",
    "colorcon",
    "basf pharma",
    "lonza",
    "catalent",
    # scripts/seed_demo_data.py vendors
    "pharmachem supplies",
    "biolabs inc",
    "medpack solutions",
}

# Fake email domains/patterns generated by seed code
SAMPLE_EMAIL_PATTERNS = (
    "@teva001.com",
    "@sand001.com",
    "@drl001.com",
    "@caps001.com",
    "@colr001.com",
    "@basf001.com",
    "@lonz001.com",
    "@catl001.com",
    "@pharmachem.example.com",
    "@biolabs.example.com",
    "@medpack.example.com",
    "contact@demo",
)


def _is_sample_row(vendor: Vendor) -> bool:
    """Return True only when the row looks like seeded demo data."""
    # Hard protection: any real DSCSA identifier → never touch it
    if vendor.gln or vendor.dea_number or vendor.state_license_number:
        return False

    # Explicit provenance tag
    if vendor.data_source == "demo":
        return True

    name_lower = (vendor.name or "").lower().strip()
    email_lower = (vendor.contact_email or "").lower().strip()

    name_match = name_lower in SAMPLE_NAMES
    email_match = email_lower and any(pat in email_lower for pat in SAMPLE_EMAIL_PATTERNS)

    return name_match or email_match


def run(apply: bool = False) -> None:
    db = SessionLocal()
    try:
        total_before = db.query(Vendor).count()
        all_vendors = db.query(Vendor).all()

        targets = [v for v in all_vendors if _is_sample_row(v)]

        if not targets:
            print("No sample/demo trading partner rows found. Nothing to do.")
            print(f"  Total vendor rows: {total_before}")
            return

        print(f"{'DRY RUN — ' if not apply else ''}Sample rows identified: {len(targets)}")
        print("-" * 70)
        print(f"{'ID':<6}  {'Name':<35}  {'Email':<30}  {'Source'}")
        print("-" * 70)
        for v in targets:
            print(f"{v.id:<6}  {(v.name or '')[:35]:<35}  {(v.contact_email or '')[:30]:<30}  {v.data_source or 'null'}")

        print("-" * 70)

        if not apply:
            print(f"\nDRY RUN complete. {len(targets)} row(s) would be deleted.")
            print("Re-run with --apply to actually delete.")
            return

        for v in targets:
            db.delete(v)
        db.commit()

        total_after = db.query(Vendor).count()
        print(f"\nDeleted {len(targets)} sample row(s).")
        print(f"  Before: {total_before}  After: {total_after}")

    except Exception as e:
        db.rollback()
        print(f"Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Remove demo/sample trading partner rows.")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete rows. Without this flag the script is a dry run.",
    )
    args = parser.parse_args()
    run(apply=args.apply)
